# Generated by Django 4.2.11 on 2024-04-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='flan',
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.carrito')),
                ('flan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.flan')),
            ],
        ),
    ]
