# Generated by Django 4.2.11 on 2024-04-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_carrito_flan_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
